---
title: Control de excepciones
description: Conozca los aspectos básicos del control de excepciones en F# y encuentre vínculos a las expresiones y funciones de control de excepciones.
ms.date: 05/16/2016
ms.openlocfilehash: 0f4e57bfd643cba3dab5281df484ebb6162cb4b7
ms.sourcegitcommit: 8699383914c24a0df033393f55db3369db728a7b
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 05/15/2019
ms.locfileid: "65645476"
---
# <a name="exception-handling"></a><span data-ttu-id="83554-103">Control de excepciones</span><span class="sxs-lookup"><span data-stu-id="83554-103">Exception Handling</span></span>

<span data-ttu-id="83554-104">Esta sección contiene información sobre la compatibilidad con el control de excepciones del lenguaje F#.</span><span class="sxs-lookup"><span data-stu-id="83554-104">This section contains information about exception handling support in the F# language.</span></span>

## <a name="exception-handling-basics"></a><span data-ttu-id="83554-105">Fundamentos del control de excepciones</span><span class="sxs-lookup"><span data-stu-id="83554-105">Exception Handling Basics</span></span>
<span data-ttu-id="83554-106">El control de excepciones es la manera estándar de controlar las condiciones de error en .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="83554-106">Exception handling is the standard way of handling error conditions in the .NET Framework.</span></span> <span data-ttu-id="83554-107">Por tanto, cualquier lenguaje de .NET debe admitir este mecanismo, incluso F#.</span><span class="sxs-lookup"><span data-stu-id="83554-107">Thus, any .NET language must support this mechanism, including F#.</span></span> <span data-ttu-id="83554-108">Una *excepción* es un objeto que encapsula la información sobre un error.</span><span class="sxs-lookup"><span data-stu-id="83554-108">An *exception* is an object that encapsulates information about an error.</span></span> <span data-ttu-id="83554-109">Cuando se producen errores, se generan excepciones y se detiene la ejecución regular.</span><span class="sxs-lookup"><span data-stu-id="83554-109">When errors occur, exceptions are raised and regular execution stops.</span></span> <span data-ttu-id="83554-110">En su lugar, el tiempo de ejecución busca un controlador adecuado para la excepción.</span><span class="sxs-lookup"><span data-stu-id="83554-110">Instead, the runtime searches for an appropriate handler for the exception.</span></span> <span data-ttu-id="83554-111">La búsqueda se inicia en la función actual y continúa hasta la pila a través de los niveles de llamadores hasta que se encuentra un controlador coincidente.</span><span class="sxs-lookup"><span data-stu-id="83554-111">The search starts in the current function, and proceeds up the stack through the layers of callers until a matching handler is found.</span></span> <span data-ttu-id="83554-112">Después, se ejecuta el controlador.</span><span class="sxs-lookup"><span data-stu-id="83554-112">Then the handler is executed.</span></span>

<span data-ttu-id="83554-113">Además, cuando se desenreda la pila, el tiempo de ejecución ejecuta cualquier código en bloques `finally`, para garantizar que los objetos se limpien correctamente durante el proceso de desenredo.</span><span class="sxs-lookup"><span data-stu-id="83554-113">In addition, as the stack is unwound, the runtime executes any code in `finally` blocks, to guarantee that objects are cleaned up correctly during the unwinding process.</span></span>

## <a name="related-topics"></a><span data-ttu-id="83554-114">Temas relacionados</span><span class="sxs-lookup"><span data-stu-id="83554-114">Related Topics</span></span>

|<span data-ttu-id="83554-115">Título</span><span class="sxs-lookup"><span data-stu-id="83554-115">Title</span></span>|<span data-ttu-id="83554-116">Descripción</span><span class="sxs-lookup"><span data-stu-id="83554-116">Description</span></span>|
|-----|-----------|
|[<span data-ttu-id="83554-117">Tipos de excepción</span><span class="sxs-lookup"><span data-stu-id="83554-117">Exception Types</span></span>](exception-types.md)|<span data-ttu-id="83554-118">Describe cómo declarar un tipo de excepción.</span><span class="sxs-lookup"><span data-stu-id="83554-118">Describes how to declare an exception type.</span></span>|
|[<span data-ttu-id="83554-119">Excepciones: El `try...with` expresión</span><span class="sxs-lookup"><span data-stu-id="83554-119">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)|<span data-ttu-id="83554-120">Describe la construcción de lenguaje que admite el control de excepciones.</span><span class="sxs-lookup"><span data-stu-id="83554-120">Describes the language construct that supports exception handling.</span></span>|
|[<span data-ttu-id="83554-121">Excepciones: El `try...finally` expresión</span><span class="sxs-lookup"><span data-stu-id="83554-121">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)|<span data-ttu-id="83554-122">Describe la construcción de lenguaje que permite ejecutar código de limpieza cuando se desenreda la pila al producirse una excepción.</span><span class="sxs-lookup"><span data-stu-id="83554-122">Describes the language construct that enables you to execute clean-up code as the stack unwinds when an exception is thrown.</span></span>|
|<span data-ttu-id="83554-123">[Exceptions: the `raise` Function](the-raise-Function.md) (Excepciones: la función `raise`)</span><span class="sxs-lookup"><span data-stu-id="83554-123">[Exceptions: the `raise` Function](the-raise-Function.md)</span></span>|<span data-ttu-id="83554-124">Describe cómo iniciar un objeto de excepción.</span><span class="sxs-lookup"><span data-stu-id="83554-124">Describes how to throw an exception object.</span></span>|
|[<span data-ttu-id="83554-125">Excepciones: El `failwith` (función)</span><span class="sxs-lookup"><span data-stu-id="83554-125">Exceptions: The `failwith` Function</span></span>](the-failwith-function.md)|<span data-ttu-id="83554-126">Describe cómo generar una excepción general de F#.</span><span class="sxs-lookup"><span data-stu-id="83554-126">Describes how to generate a general F# exception.</span></span>|
|[<span data-ttu-id="83554-127">Excepciones: El `invalidArg` (función)</span><span class="sxs-lookup"><span data-stu-id="83554-127">Exceptions: The `invalidArg` Function</span></span>](the-invalidArg-function.md)|<span data-ttu-id="83554-128">Describe cómo generar una excepción de argumento no válido.</span><span class="sxs-lookup"><span data-stu-id="83554-128">Describes how to generate an invalid argument exception.</span></span>|
