---
title: Error del compilador CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: 7ea5e861b71f5f65231bb29537a28a23a0821cef
ms.sourcegitcommit: 10986410e59ff29f2ec55c6759bde3eb4d1a00cb
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 05/31/2019
ms.locfileid: "66422966"
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="fdb80-102">Error del compilador CS0156</span><span class="sxs-lookup"><span data-stu-id="fdb80-102">Compiler Error CS0156</span></span>
<span data-ttu-id="fdb80-103">No se permite una instrucción throw sin argumentos en una cláusula finally anidada en la cláusula catch más cercana</span><span class="sxs-lookup"><span data-stu-id="fdb80-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="fdb80-104">Una instrucción [throw](../../csharp/language-reference/keywords/throw.md) sin parámetros solo puede aparecer en una cláusula **catch** que no tome parámetros.</span><span class="sxs-lookup"><span data-stu-id="fdb80-104">A [throw](../../csharp/language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="fdb80-105">Para obtener más información, consulte [excepciones y control de excepciones](../../csharp/programming-guide/exceptions/index.md).</span><span class="sxs-lookup"><span data-stu-id="fdb80-105">For more information, see [Exceptions and Exception Handling](../../csharp/programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="fdb80-106">El ejemplo siguiente genera la advertencia CS0156:</span><span class="sxs-lookup"><span data-stu-id="fdb80-106">The following sample generates CS0156:</span></span>  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
